### ISSUE TITLE
use proxy for rpc

### ISSUE THREAD

**Issue by Tocard** [HopersNFT/hopers-frontend#62]
you're changing rpc in code, use a proxy with rourndrobin to avoid ban. (gonna change rpc each call)

that's NOT a perma fix but gonna give some breath.

haproxy for example could help in this case (this is the one I know better)

https://www.haproxy.com/blog/the-four-essential-sections-of-an-haproxy-configuration/

**Comment by Dizz02** [comment]
thank you
