### ISSUE TITLE
Use backend with cache

### ISSUE THREAD

**Issue by Tocard** [HopersNFT/hopers-frontend#63]
You should export some feature to a dedicated backend with cache to use ressources efficiencly & wisely

**Comment by sheriff-rango** [comment]
Hi @Tocard
Thanks for your comment.
Yeah, I am doing that to optimize the project.
I hope you discuss this in more detail if you don't mind.
I think discord is good for discussing.
May I get your discord username so that I can DM you.
Thank you.

**Comment by Tocard** [comment]
> Hi @Tocard Thanks for your comment. Yeah, I am doing that to optimize the project. I hope you discuss this in more detail if you don't mind. I think discord is good for discussing. May I get your discord username so that I can DM you. Thank you.

I already have acces to the dev part of discord (Douceur) is my name.

**Comment by Tocard** [comment]
![image](https://user-images.githubusercontent.com/6951742/213989716-fef189f5-a775-4798-bfcb-db15c9fd3742.png)
realy simple pattern
